import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Users",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container" style={{ fontFamily: 'var(--font-geist-sans)' }}>
        <div className="Header">
          <h1>USERS</h1>
          <Link href="/">Anasayfa</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
